# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_family',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_end',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
